# Generated by Django 4.1.2 on 2022-10-14 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_rename_lessons_lesson'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Teachers',
            new_name='CourseTeachers',
        ),
    ]
