# Generated by Django 4.1.2 on 2022-10-14 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_rename_teachers_courseteachers'),
        ('mainapp', 'migration_custom'),
    ]

    operations = [
    ]
